### ISSUE TITLE
Données personnelles ?

### ISSUE THREAD

**Issue by dofbi** [ctkhoule/XML-Gestion-Imputation#1]
Salaam @ctkhoule 
Un sujet sensible de nos jours les données personnelles est ce une démo ou de vrais noms du personnelles de UASZ ?

Tu peux te refaire sur le document suivant pour les [données personnelles](https://www.wipo.int/edocs/lexdocs/laws/fr/sn/sn009fr.pdf)

**Comment by ctkhoule** [comment]
Salm
C'est juste une démo. Ceux ne sont pas des noms du personnel.
Merci pour le rappel.

Le sam. 20 févr. 2021 à 20:03, Mamadou Diagne <notifications@github.com> a
écrit :

**Comment by ctkhoule** [comment]
Merci pour le document, je vais le consulter.

**Comment by ctkhoule** [comment]
Le projet est mis à jour.

**Comment by dofbi** [comment]
Good grand
